num1=int(input("Enter Number of 1=\n"))
num2=int(input("Enter Number of 2=\n"))
num3=int(input("Enter Number of 3=\n"))
num4=int(input("Enter Number of 4=\n"))
num5=int(input("Enter Number of 5=\n"))
num6=int(input("Enter Number of 6=\n"))
num7=int(input("Enter Number of 7=\n"))
num8=int(input("Enter Number of 8=\n"))
s={num1,num2,num3,num4,num5,num6,num7,num8}
print(s)